### ISSUE TITLE
Undefined written if no example is returned by API

### ISSUE THREAD

**Issue by saglaniharsh** [ashawe/Word-Meanings-to-Markdown#1]
**Current Scenario**
Currently, there is no checking done regarding whether an example is present in the API response or not.
It is assumed that the example is always present.
If the example is not present 'undefined' is written in the file (as the data is undefined in JSON response).

**Expected Scenario**
It should be checked whether example is present or not in the JSON response.
if it is not, do not write ```ex: undefined``` in the file. 

Most pertains to [this line](https://github.com/ashawe/Word-Meanings-to-Markdown/blob/master/index.js#L56)

**Comment by saraogipraveen** [comment]
Hi @ashawe, I want to take this up. Please assign
