### ISSUE TITLE
Undefined written if synonyms are less than 5

### ISSUE THREAD

**Issue by saglaniharsh** [ashawe/Word-Meanings-to-Markdown#2]
**Current Scenario**
It is assumed that there will be more than 5 synonyms per definition. If no synonym is present ```undefined``` is written in the file.

**Expected Scenario**
run the loop for synonyms for ```min(synonyms.length,5)``` where synonyms is the array of synonyms in the definition section of the JSON response.

Mostly pertains to [this line](https://github.com/ashawe/Word-Meanings-to-Markdown/blob/master/index.js#L60)

**Comment by saraogipraveen** [comment]
Hi @ashawe 

Basically all the synonyms of every definition should get merge together and get displayed right? or do we have to keep any maximum limit for synonyms to be displayed?

**Comment by saglaniharsh** [comment]
> 
> 
> Hi @ashawe
> 
> Basically all the synonyms of every definition should get merge together and get displayed right? or do we have to keep any maximum limit for synonyms to be displayed?

Yeah so basically, I chose a limit of 5 per definition because sometimes there are like 20 synonyms for a definition

**Comment by saraogipraveen** [comment]
> > Hi @ashawe
> > Basically all the synonyms of every definition should get merge together and get displayed right? or do we have to keep any maximum limit for synonyms to be displayed?
> 
> Yeah so basically, I chose a limit of 5 per definition because sometimes there are like 20 synonyms for a definition

Ohh! Seems like I removed that limit and displayed whatever list of synonyms we get. You want me to add that limit of 5 again?

**Comment by saglaniharsh** [comment]
> 
> Ohh! Seems like I removed that limit and displayed whatever list of synonyms we get. You want me to add that limit of 5 again?

I guess it should depend on the user about how many synonyms they want. I didn't set a limit overall but set a limit per definition because if the limit is overall, it might happen that synonyms of one definition reach up to that limit and others just get skipped. That's why the problem of undefined was there. I believe we should actually give users the choice and set some defaults and global variables but that would be too much work I guess.

What we can do is set a default limit per definition and that's it (for now). The user can change the default in the source code if they want to right?

**Comment by saglaniharsh** [comment]
@saraogipraveen any updates?

**Comment by saraogipraveen** [comment]
> @saraogipraveen any updates?

Do you want me to add a limit up to 5 as of now?

**Comment by saglaniharsh** [comment]
> 
> 
> > @saraogipraveen any updates?
> 
> Do you want me to add a limit up to 5 as of now?

Yes you can make a GLOBAL variable and add set a limit.
```
IF LIMIT <> 0 THEN
	PUSH LIMIT NUMBER OF SYNONYMS
ELSE
	PUSH ALL SYNONYMS
```
also make sure it isn't negative (throw error)

**Comment by saraogipraveen** [comment]
Hi @ashawe, Please add hactoberfest topic to this repo as per Hactoberfet Update 
refer - https://twitter.com/hacktoberfest/status/1312221208667185153

**Comment by saraogipraveen** [comment]
![image](https://user-images.githubusercontent.com/16433473/95018418-4ac47600-067d-11eb-8d1e-84737fae553d.png)


> Hi @ashawe, Please add hactoberfest topic to this repo as per Hactoberfet Update
> refer - https://twitter.com/hacktoberfest/status/1312221208667185153

**Comment by saglaniharsh** [comment]
@saraogipraveen I did
